[Feat] Dockerfile: demo-page
GirinMan/HAI-2023-RAG pull request #5
Opened 2023-11-21 13:01 UTC by DHki

데모 페이지 dockerfile입니다!

requirements.txt.에서 langchain이 없어서, 추가했습니다.

2023-11-21 22:45 UTC, GirinMan requested changes
고치느라 고생하셨습니다.

2023-11-21 22:45 UTC, GirinMan commented on streamlit_app/Dockerfile
> +CMD ["streamlit", "run", "/app/src/app.py", "--server.port", "40201"]
컨테이너 내부 포트는 80으로 해주시고, docker compose에서 포워딩하도록 변경해주세요.
40201 말고도 다른 포트를 쓸 수도 있으니...

2023-11-21 22:45 UTC, GirinMan commented on docker-compose.yaml
> +    container_name: chat_demo
채팅 데모에 업로드한 파일 저장되는 경로가 있는데, 외부에서도 업로드된 파일 확인할 수 있게 디렉토리 마운트하도록 하먼 좋을것 갘아요

2023-11-21 22:45 UTC, GirinMan commented on streamlit_app/Dockerfile
> +EXPOSE 8080
8080 expose하신 이유가 있을까요?

2023-11-22 06:37 UTC, DHki commented on streamlit_app/Dockerfile
> +EXPOSE 8080
이 부분은 네트워크 수정하면서 안고쳤던 것 같습니다..!! 수정해 놓을게용

2023-11-22 06:41 UTC, DHki commented on streamlit_app/Dockerfile
> +CMD ["streamlit", "run", "/app/src/app.py", "--server.port", "40201"]
이 부분 관련해서, 컨테이너 내부적으로 localhost를 호출하는 경우가 있더라구요..! 그러려면 IP를 호스트와 동일하게 전달해줘야 하는 것으로 알고 있는데, 내부적으로 바꾸면 localhost 호출에 문제가 있을 수 있지 않을까요??

docker bridge 모드에서 할당 받는 내부 IP(172.XXX.XXX.XXX)을 이용하도록 데모 페이지를 수정하고 포트 연결을 할까요?

2023-12-02 18:54 UTC, hyunwoo3235 approved these changes
수정 완료

2023-12-02 18:54 UTC, merged